name: quantum
parent: default

matches:
  - trigger: "\\\\to"
    replace: "→"
  - trigger: "\\\\bn"
    replace: "ℕ"
  - trigger: "\\\\br"
    replace: "ℝ"
  - trigger: "\\\\pi"
    replace: "π"
  - trigger: "\\\\bb"
    replace: "𝔹"
  - trigger: "\\\\cdot"
    replace: "⋅"
  - trigger: "\\\\theta"
    replace: "θ"
  - trigger: "\\\\psi"
    replace: "ψ"
  - trigger: "\\\\lambda"
    replace: "λ"
  - trigger: "\\\\neg"
    replace: "¬"
  - trigger: "\\\\times"
    replace: "×"
  - trigger: "\\\\pm"
    replace: "±"
  - trigger: "\\\\b1"
    replace: "𝟙"
  - trigger: "\\\\bra"
    replace: "⟨"
  - trigger: "\\\\ket"
    replace: "⟩"
